# Site settings
author: Allen Pottinger
title: Cheat Codes
header-img: img/home-bg.png
email: allenpottinger@gmail.com
copyright_name: Allen Pottinger
description: > # this means to ignore newlines until "baseurl:"
  for Coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  APottinger

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
